openapi: 3.0.0
info:
  contact: {}
  description: This REST API provides endpoints to search for earnings call transcripts and get earnings call transcript details.
  termsOfService: http://swagger.io/terms/
  title: Earnings Call Transcripts API
  version: 1.0.0
paths:
  /api/v1/earnings-call-transcripts:
    get:
      description: Get Earnings Call Transcripts
      operationId: get-earnings-call-transcripts
      parameters:
        - description: Tickers
          in: query
          name: tickers
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - description: Call ID
          in: query
          name: call_id
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - description: Page
          in: query
          name: page
          schema:
            type: integer
        - description: Page Size
          in: query
          name: pagesize
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/models.TranscriptSummary"
                type: array
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
      security:
        - ApiKeyAuth: []
      summary: Get Earnings Call Transcripts
      tags:
        - Earnings Call Transcripts
  /api/v1/earnings-call-transcripts/audio:
    get:
      description: Get Earnings Call Transcript Audio Files
      operationId: get-earnings-call-transcript-audio-files
      parameters:
        - description: Tickers
          in: query
          name: tickers
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - description: Call ID
          in: query
          name: call_id
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - description: Page
          in: query
          name: page
          schema:
            type: integer
        - description: Page Size
          in: query
          name: pagesize
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/models.TranscriptSummaryAudio"
                type: array
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
      security:
        - ApiKeyAuth: []
      summary: Get Earnings Call Transcript Audio Files
      tags:
        - Earnings Call Transcripts
components:
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: Authorization
      type: apiKey
  schemas:
    models.Security:
      properties:
        cik:
          type: string
        company_name:
          type: string
        exchange:
          type: string
        isin:
          type: string
        ticker:
          type: string
      type: object
    models.Summary:
      properties:
        summary:
          type: string
        time:
          type: number
      type: object
    models.TranscriptAudioFile:
      properties:
        file_url:
          type: string
      type: object
    models.TranscriptSummary:
      properties:
        call_id:
          type: string
        created:
          type: integer
        date:
          type: string
        id:
          type: string
        reviewed:
          type: boolean
        security:
          $ref: "#/components/schemas/models.Security"
        start_time:
          type: string
        summaries:
          items:
            $ref: "#/components/schemas/models.Summary"
          type: array
        summary_full:
          type: string
        title:
          type: string
        transcript_full:
          type: string
        transcript_timestamped:
          items:
            $ref: "#/components/schemas/models.TranscriptTimestamp"
          type: array
        updated:
          type: integer
        user_id:
          type: integer
      type: object
    models.TranscriptSummaryAudio:
      properties:
        audio_file:
          $ref: "#/components/schemas/models.TranscriptAudioFile"
        call_id:
          type: string
        created:
          type: integer
        date:
          type: string
        id:
          type: string
        security:
          $ref: "#/components/schemas/models.Security"
        start_time:
          type: string
        updated:
          type: integer
      type: object
    models.TranscriptTimestamp:
      properties:
        time:
          type: number
        transcript:
          type: string
      type: object
servers:
  - url: https://api.benzinga.com/api/v1
    description: V1
