name: Process OpenAPI Files

on:
  push:
    branches:
      - main 
  workflow_dispatch: # Allows the action to be triggered manually

jobs:
  process_openapi_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Debug OpenAPI processing script
      run: |
        echo "Listing files in ./openapi:"
        ls -la ./openapi

        for file in ./openapi/*.yml; do
          echo "Processing file: $file"

          filename=$(basename "$file" .spec.yml)
          echo "Filename without extension: $filename"

          mkdir -p "$filename"
          cd ./$filename

          command_output=$(npx @mintlify/scraping@latest openapi-file ../$file | tail -n +2)

          echo "Command output:"
          echo "$command_output"

          merged_pages=$(echo "$command_output" | jq -s '[.[][] | .pages[]]')

          echo "Merged pages:"
          echo "$merged_pages"

          if ! jq -e . >/dev/null 2>&1 <<<"$merged_pages"; then
            echo "Invalid JSON in merged_pages" >&2
            exit 1
          fi

          output=$(jq -n --argjson pages "$merged_pages" --arg filename "$filename" '{"group": $filename, "pages": $pages}')
          echo "Final output JSON:"
          echo "$output"

          cd ../
        done
